/*
 * Copyright (c) 2025-2026 Dylan Storey
 * Licensed under the Elastic License 2.0.
 * See LICENSE file in the project root for full license text.
 */

/**
 * Auto-generated TypeScript client for the Brokkr broker API.
 *
 * - {@link schema} is the source of truth, regenerated by
 *   `angreal openapi gen-typescript` from `openapi/brokkr-v1.json`.
 * - {@link createBrokkrClient} returns a typed `openapi-fetch` client. Every
 *   path, method, and body is checked against the spec at compile time.
 *
 * The ergonomic wrapper (auth header injection, retry/backoff, `BrokkrError`
 * with `.code` matching) lives next to this in `src/client.ts` once T-C4
 * lands. This file is the thin wire layer that mirrors what
 * `crates/brokkr-client` (Rust) and `sdks/python/brokkr-client` (Python)
 * produce.
 */

import createClient, { type ClientOptions } from "openapi-fetch";

import type { components, paths } from "./schema.js";

/** All API operations keyed by path + method. */
export type { paths, components } from "./schema.js";

/** Convenience aliases for commonly referenced schema types. */
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type Agent = components["schemas"]["Agent"];
export type Stack = components["schemas"]["Stack"];
export type WorkOrder = components["schemas"]["WorkOrder"];
export type WorkOrderLog = components["schemas"]["WorkOrderLog"];
export type DeploymentObject = components["schemas"]["DeploymentObject"];
export type StackTemplate = components["schemas"]["StackTemplate"];
export type AuthResponse = components["schemas"]["AuthResponse"];
export type WebhookResponse = components["schemas"]["WebhookResponse"];
export type PendingWebhookDelivery = components["schemas"]["PendingWebhookDelivery"];
// WS-10 / WS-13 — internal broker↔agent channel surface (BROKKR-I-0019).
// These are the response shapes the ergonomic wrapper methods return.
export type K8sEventHistoryResponse =
  components["schemas"]["K8sEventHistoryResponse"];
export type PodLogHistoryResponse =
  components["schemas"]["PodLogHistoryResponse"];
export type RetentionInfo = components["schemas"]["RetentionInfo"];
export type WsConnectionsResponse =
  components["schemas"]["WsConnectionsResponse"];
export type WsConnectionInfo = components["schemas"]["WsConnectionInfo"];

/**
 * Construct a typed openapi-fetch client for the Brokkr broker API.
 *
 * Pass `headers: { Authorization: "Bearer <pak>" }` (or a fetch interceptor)
 * to authenticate. For a single-credential, retry-capable wrapper see the
 * ergonomic layer added by T-C4.
 */
export function createBrokkrClient(options: ClientOptions = {}) {
  return createClient<paths>(options);
}

/** The concrete client type, useful for typing wrapper fields. */
export type BrokkrApi = ReturnType<typeof createBrokkrClient>;

// Ergonomic wrapper layer (T-C4).
export { BrokkrClient } from "./client.js";
export type { BrokkrClientOptions } from "./client.js";
export { BrokkrError } from "./error.js";
