[package]
name = "brokkr-agent"
version = "0.0.0"
edition = "2021"

[lib]
name = "brokkr_agent"
path = "src/lib.rs"

[[bin]]
name = "brokkr_agent"
path = "src/bin.rs"

[dependencies]
brokkr-broker = { path = "../brokkr-broker" }
brokkr-models = { path = "../brokkr-models" }
brokkr-utils = { path = "../brokkr-utils" }
axum = { workspace = true }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
# kube = { version = "0.56" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"