[package]
name = "brokkr-models"
version = "0.0.0"
edition = "2021"

[dependencies]
diesel = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenv = { workspace = true }
chrono = { workspace = true }
brokkr-utils = { path = "../brokkr-utils" }
sha2 = { workspace = true }
diesel-derive-enum = { version = "2.0", features = ["postgres"] }


[dev-dependencies]
url = {version = "^2.4.0"}
diesel_migrations = "2.1.0"
