---
name: Data Model Tests
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://brokkr:brokkr@localhost:5432/brokkr
jobs:
  data_model_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: brokkr
          POSTGRES_PASSWORD: brokkr
          POSTGRES_DB: brokkr
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install angreal
        run: |
          python -m pip install --upgrade pip
          pip install angreal
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
        run: cargo install diesel_cli
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-rust-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-rust-build-${{ github.sha }}
      - name: Run data models test
        run: angreal models test --skip-docker
        working-directory: ${{ inputs.data-model-path }}
      - name: Run migration tests
        run: angreal models  migrations --skip-docker
        working-directory: ${{ inputs.data-model-path }}
