---
name: Setup
on:
  workflow_call:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: python-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-angreal
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install angreal
        if: steps.python-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install angreal

      - name: Rust Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build workspace
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets
